<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>factspdf</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../FactsPDF/FactsPDF.csproj" /></ItemGroup>
</Project>
