<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <PackageId>FactsPDF</PackageId>
    <Description>A browser-free HTML and CSS to PDF engine, designed for cross-language integration.</Description>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/KoalaFacts/FactsPDF</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../LICENSE.md" Pack="true" PackagePath="/" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
